channels:
 - conda-forge
 - nodefaults
dependencies:
  - pandas
  - mamba
  - pip
  - sphinx
  - furo
  - cupy
  - mpmath
  - dataclasses
  - sympy
  - numpy
  - matplotlib
  - pytest
  - scipy

platforms:
  - linux-64