name: master-thesis-code
channels:
 - conda-forge
 - nodefaults
dependencies:
  - python
  - mamba
  - pip
  - gcc_linux-64
  - gxx_linux-64
  - wget
  - lapack=3.6.1
  - hdf5
  - gsl
  - numpy
  - Cython
  - scipy
  - tqdm
  - jupyter
  - ipython
  - h5py
  - requests
  - matplotlib
  - sphinx
  - furo

platforms:
  - linux-64